### ISSUE TITLE
Revamp the side navigation menu

### ISSUE THREAD

**Issue by pushkar-dev** [pushkar-dev/community-yard#7]
Tasks-
1. Remove the icons marked in red, possibly delete the corresponding code of website reposter.
2. create new icons for the items marked in green and move them from sub menu to the main menu. Come up with new relevent icons from the icon packs used.
3. Remove the home icon but make the text Community-Yard  a link to home page.   
![image](https://github.com/pushkar-dev/community-yard/assets/79650452/0407f359-54fc-4e59-b34b-f4b3582b80cb)

**Comment by Sabbirfeni** [comment]
@pushkar-dev I am  interested on update this sidebar. Please assign this issue to me.

**Comment by pushkar-dev** [comment]
> @pushkar-dev I am interested on update this sidebar. Please assign this issue to me.

@Sabbirfeni I am currently guiding a team of juniors at my college to get some experience in web development, i was hoping that one of them would take this up as a kickstarter. I am sorry but I will be opening some other cool issues to contribute in future.

**Comment by Sabbirfeni** [comment]
It's okay. I will be looking for the next chance.

**Comment by Sabbirfeni** [comment]
Btw are you CS student?

**Comment by Prathme07** [comment]
I want to pick this issue

**Comment by pushkar-dev** [comment]
#16 please remove the code corresponding to these features also
